import Head from 'next/head'

/**
 * server side
 * @param {*} context 
 * @returns 
 */
export async function getServerSideProps(context) {
  // global define
  const api = process.env.ARCTICLE_API_URL;
  const cities = await (await fetch(`${api}/city`)).json()
  const needs = await (await fetch(`${api}/need`)).json()

  //
  return {
    props: { cities, needs },
  }
}

/**
 * client side
 * @param {*} properties 
 * @returns 
 */
export default function Home({ cities, needs }) {

  //
  return (
    <>
      <Head>
        <title>Help</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='container'>

          <form className='was-validated row gy-2 gx-3'>

            <div className='col-auto'>
              <select className='form-select' placeholder='city name' required>
                {
                  cities.map((city) => {
                    return <option key={city._id}>{city.cityName}</option>
                  })
                }
              </select>
            </div>

            <div className='col-auto'>
              <select className='form-select' placeholder='type of need' required>
                {
                  needs.map((need) => {
                    return <option key={need._id}>{need.kind}</option>
                  })
                }
              </select>
            </div>

            <div className='col-auto'>
              <button className='btn btn-success' type='submit'>Help Request</button>
            </div>

          </form>
        </div>
      </main>
    </>
  )
}
